### PR TITLE
French translation update

### PR DESCRIPTION
**Pull request by trebmuh**

### CODE REVIEW

**Comment by x42** [comment]
Just a heads-up: Since v0.8.0  (summer 2014), the QT remote-control GUI which you've translated is deprecated and no longer built by default (official binaries don't include it, nor do debian packages).

xjadeo has a built-in menu these days (and that is not translatable). 

That being said: the qt-gui still works and will keep working (remote-control interface will remain backwards compatible) but I won't maintain it and it'll likely vanish with QT4.

**Comment by trebmuh** [comment]
OK, good to know. I've rebuild a package from Debian Jessie (0.8.0), and the GUI is still translatable so I assume that you refer to the debian stretch package (0.8.7) when you say that the Qt GUI isn't build anymore for debian.

Any plan to make the current new built-in menu translatable maybe?

**Comment by x42** [comment]
You can still  `./configure --enable-qtgui` if needed.  it's been dropped for  debian/stretch

**Comment by trebmuh** [comment]
Thanks.

**Pull request merged**
